### ISSUE TITLE
Edit from Teaching Loads Tab

### ISSUE THREAD

**Issue by Jdellis818** [senior-knights/course-schedulizer#117] opened 2021-02-24 01:18 UTC

**Comment by charkour** [comment] 2021-03-06 21:24
Closing this issue because it is a duplicate of #141, but 141 has a description from @kvlinden and will be closed on PR #130

**Comment by charkour** [comment] 2021-03-06 21:25
At least, I think it's a duplicate. Can be reopened if I'm wrong.

**Closed as completed** 2021-03-06 21:24 UTC
Labels: duplicate

**Comment by kvlinden** [comment] 2021-03-06 22:02
I thought that this was was to support editing of courses on the teaching loads tab?

**Comment by charkour** [comment] 2021-03-09 13:21
Confirmed with @Jonri2, this is a duplicate. Thanks!
